# Generated by Django 5.2.1 on 2026-05-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id_enfant', models.AutoField(primary_key=True, serialize=False)),
                ('naissance', models.DateField(blank=True, null=True)),
                ('prenom', models.CharField(max_length=50)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Enfant',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('id_enfant', models.ForeignKey(db_column='id_enfant', on_delete=django.db.models.deletion.CASCADE, to='api.enfant')),
            ],
            options={
                'db_table': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id_detection', models.AutoField(primary_key=True, serialize=False)),
                ('emotion', models.CharField(choices=[('joie', 'Joie'), ('tristesse', 'Tristesse'), ('colere', 'Colere'), ('surprise', 'Surprise')], max_length=20)),
                ('heure', models.DateTimeField()),
                ('important', models.BooleanField(default=False)),
                ('id_session', models.ForeignKey(db_column='id_session', on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
            options={
                'db_table': 'Detections',
            },
        ),
    ]
