# Generated by Django 5.2.1 on 2026-05-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id_profil', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motdepasse', models.CharField(max_length=255)),
                ('naissance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('id_profil', models.ForeignKey(db_column='id_profil', on_delete=django.db.models.deletion.CASCADE, to='api.profil')),
            ],
            options={
                'db_table': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id_detection', models.AutoField(primary_key=True, serialize=False)),
                ('heure', models.DateTimeField()),
                ('landmarks', models.JSONField()),
                ('important', models.BooleanField()),
                ('id_session', models.ForeignKey(db_column='id_session', on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
            options={
                'db_table': 'Detections',
            },
        ),
    ]
