# Generated by Django 5.2.1 on 2026-06-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='dernier_telechargement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
